### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by metalelf0** [datsfilipe/vesper.nvim#1]
Hey there :) Great colorscheme, looking good!

In the README file there's a small typo:

```lua
    highlights = require('vesper').bufferline.highlights(),
    -- should instead be
    highlights = require('vesper').bufferline.highlights,
```

Keep up the great work!

**Comment by datsfilipe** [comment]
Oh thanks, I'm gonna change it.

Also, thank you for the kind words!
